### ISSUE TITLE
[Insight] A Symfony application should be bootable

### ISSUE THREAD

**Issue by joshavg** [laniger/OmgDb#15]
> SensioLabsInsight was not able to boot your Symfony application. If you need to customize files or run commands to make it bootable, you can edit your SensioLabsInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.Heads up! Since this is a new violation, it may explain why other violations have disappeared: SensioLabsInsight needs to boot Symfony applications in order to make dynamic checks.

```
Symfony\Component\Config\Definition\Exception\InvalidTypeException: Invalid type for path &quot;laniger_neo4j.port&quot;. Expected int, but got NULL. in /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/IntegerNode.php:29
Stack trace:
#0 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(261): Symfony\Component\Config\Definition\IntegerNode->validateType(NULL)
#1 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(307): Symfony\Component\Config\Definition\BaseNode->normalize(NULL)
#2 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#3 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(33): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#4 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(50): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array)
#5 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Extension/Extension.php(103): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(laniger\Neo4jBundle\DependencyInjection\Configuration), Array)
#6 /home/foobar/code/src/laniger/Neo4jBundle/DependencyInjection/lanigerNeo4jExtension.php(20): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration(Object(laniger\Neo4jBundle\DependencyInjection\Configuration), Array)
#7 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(55): laniger\Neo4jBundle\DependencyInjection\lanigerNeo4jExtension->load(Array, Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#8 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(ExtendedContainerBuilder))
#9 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(107): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(ExtendedContainerBuilder))
#10 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(593): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(ExtendedContainerBuilder))
#11 phar:///home/foobar/bin/insight.phar/src/SensioLabs/Insight/Sniffer/Model/Sniffer/Resource/ExtendedContainerBuilder.php(13): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#12 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(511): ExtendedContainerBuilder->compile()
#13 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#14 /home/foobar/code/app/InsightAppKernel.php(15) : eval()&#039;d code(7): Symfony\Component\HttpKernel\Kernel->boot()
#15 /home/foobar/code/app/InsightAppKernel.php(15): eval()
#16 {main}
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/3b03deff-c9a2-49a9-820f-79c1ffd9050b/analyses/7)_

**Comment by joshavg** [comment]
Relates to #7

**Comment by joshavg** [comment]
should be fixed
